### ISSUE TITLE
/about is broken by default

### ISSUE THREAD

**Issue by InsaneNaman** [cosmicjs/nextjs-developer-portfolio#23]
Hey team, thanks for awesome product. While I was trying this repo, I've found out that the `/about` is not working. I have forked the project and fixed it. Also, I have done couple of refactoring and would like to raise the PR to fix this. You can see my fork [here 🔗](https://github.com/InsaneNaman/cosmic-nextjs-developer-portfolio)

Changes that I have done in my fork:
1- Have created new [DeveloperAvatar](https://github.com/InsaneNaman/cosmic-nextjs-developer-portfolio/blob/main/src/components/DeveloperAvatar.jsx) componen to show `animate pulse` while it loads image. It improves a bit of user experience for users on slow network.

2- Refactor `page.jsx`([see change](https://github.com/InsaneNaman/cosmic-nextjs-developer-portfolio/blob/main/src/app/page.jsx#L27)) and `about/page.jsx`([see change](https://github.com/InsaneNaman/cosmic-nextjs-developer-portfolio/blob/main/src/app/about/page.jsx#L16)) to improve the readability. (This will fix the screenshot issue as well)

Note: I can deploy on vercel or cloudflare to show the demo or record a loom video if you would like to. 

<img width="1783" alt="image" src="https://github.com/cosmicjs/nextjs-developer-portfolio/assets/13780776/014fcd83-d77b-40fe-97f5-6892305758eb">

**Comment by stefkudla** [comment]
Hey @InsaneNaman, I am checking to see if this issue still persist after the latest upgrade I've made to this template in PR #22 .

**Comment by InsaneNaman** [comment]
Hey @stefkudla sure thing. Let me know, if I can be of any help. I am exploring svelte lately and just wondering if you have any plans to put a similar repo for svelte/solid. I can try to make a simple example or clone of this project in svelte. 

cc: @tonyspiro
