### ISSUE TITLE
Category Filter Issue in /posts and /work Routes

### ISSUE THREAD

**Issue by N-dcool** [cosmicjs/nextjs-developer-portfolio#25]
In the `/posts` and `/work` routes, the category filter doesn't work as expected, failing to filter the posts correctly.

https://github.com/cosmicjs/nextjs-developer-portfolio/assets/107427909/e1f0faa5-f66b-40ab-ad5b-93e99d6e35e6

I have not edited anything in cosmic dashboard and GitHub repo :)
<img width="1438" alt="Screenshot 2023-11-08 at 8 26 35 PM" src="https://github.com/cosmicjs/nextjs-developer-portfolio/assets/107427909/3c184c58-a30d-4778-8e43-4a1361cedaed">

**Comment by tonyspiro** [comment]
Thank you for the report @N-dcool I've pushed [a fix](https://github.com/cosmicjs/nextjs-developer-portfolio/commit/5a11b8a87486931b2dd2a2f99c09faa0eec81a0a). Please update your code and let me know that it's fixed.

**Comment by N-dcool** [comment]
Thank you for your response and for addressing the issue. I appreciate your
quick action in pushing the fix.

I have updated my code as per your recommendation, and I'm pleased to
confirm that the issue has been successfully resolved. 🤩

**Comment by tonyspiro** [comment]
Great to hear. Closing this issue.
